development:
  access_key_id: AKIAICZOJNDMXYASZLUA
  secret_access_key: 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

test:
  access_key_id: AKIAICZOJNDMXYASZLUA
  secret_access_key: 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

production:
  access_key_id: AKIAICZOJNDMXYASZLUA
  secret_access_key: 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
